version: "2.0"
services:

  mariadb:
    image: mariadb:10.2
    container_name: HoHo-Mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./images/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=littlepighoho17**

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: HoHo-pma
    ports: 
      - "5840:80"
    depends_on:
      - mariadb
    links:
      - mariadb:db

  redis:
    image: redis:4.0
    container_name: HoHo-redis-primary
    volumes:
      - ./redis:/data
      - ./images/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf

  redis-secondary:
    image: redis:4.0
    container_name: HoHo-redis-secondary
    depends_on: 
      - redis
    links:
      - redis:redis
    volumes:
      - ./redis-secondary:/data
      - ./images/redis-secondary/redis-secondary.conf:/etc/redis/redis.conf
    ports:
      - "6380:6378"
    command: redis-server /etc/redis/redis.conf

  server:
    build: ./images/server
    container_name: HoHo-Server
    restart: always
    depends_on: 
      - mariadb
      - redis
      - redis-secondary
    links:
      - mariadb:mysqldb
      - redis:redis
      - redis-secondary:redis-secondary
    volumes: 
      - .:/root

  web:
    image: nginx:1.13
    container_name: HoHo-Web
    depends_on: 
      - server
      - pma
    links:
      - server:server
      - pma:pma
    ports: 
      - "80:80"
    volumes: 
      - ./nginx-dev:/etc/nginx/conf.d
    