# Generated by Django 2.1.2 on 2019-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='config',
            field=models.TextField(default='{"number_of_leave": 2, "version": 0, "version_dict": {}, "attendance_proportion": 0.3}'),
        ),
        migrations.AlterField(
            model_name='associationaccount',
            name='permissions',
            field=models.TextField(default='{"appraising": false, "notice": false, "repository": false, "task": false, "interview": false, "scheduling": false}'),
        ),
    ]
