# Generated by Django 2.1.2 on 2019-03-27 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationattendance',
            name='manager',
        ),
        migrations.AddField(
            model_name='association',
            name='backlog',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='{"attendance": {}}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associationaccount',
            name='permissions',
            field=models.TextField(default='{"interview": false, "task": false, "notice": false, "repository": false, "scheduling": false, "appraising": false}'),
        ),
        migrations.AlterField(
            model_name='association',
            name='config',
            field=models.TextField(verbose_name='{}'),
        ),
        migrations.AlterField(
            model_name='associationaccount',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, '干事'), (1, '部长'), (2, '会长'), (99, '系统管理员')], default=0),
        ),
    ]
