# Generated by Django 2.1.2 on 2019-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_auto_20190403_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='config',
            field=models.TextField(default='{"version_dict": {}, "number_of_leave": 2, "attendance_proportion": 0.3, "version": 0}'),
        ),
        migrations.AlterField(
            model_name='associationaccount',
            name='permissions',
            field=models.TextField(default='{"scheduling": false, "task": false, "appraising": false, "notice": false, "repository": false, "interview": false}'),
        ),
    ]
