# Generated by Django 2.1.2 on 2019-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_auto_20190403_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='config',
            field=models.TextField(default='{"attendance_proportion": 0.3, "number_of_leave": 2, "version_dict": {}, "version": 0}'),
        ),
        migrations.AlterField(
            model_name='associationaccount',
            name='permissions',
            field=models.TextField(default='{"appraising": false, "repository": false, "notice": false, "scheduling": false, "task": false, "interview": false}'),
        ),
    ]
