# Generated by Django 2.1.2 on 2019-03-29 23:46

import common.core.dao.time_stamp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_auto_20190329_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationattendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='associationattendance',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='association',
            name='create_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='association',
            name='update_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='associationaccount',
            name='create_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='associationaccount',
            name='permissions',
            field=models.TextField(default='{"appraising": false, "interview": false, "task": false, "notice": false, "repository": false, "scheduling": false}'),
        ),
        migrations.AlterField(
            model_name='associationaccount',
            name='update_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='associationattendance',
            name='create_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='associationattendance',
            name='update_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='associationdepartment',
            name='create_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='associationdepartment',
            name='update_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
    ]
