# Generated by Django 2.1.2 on 2019-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_auto_20190330_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationaccount',
            name='permissions',
            field=models.TextField(default='{"appraising": false, "interview": false, "notice": false, "scheduling": false, "repository": false, "task": false}'),
        ),
    ]
