# Generated by Django 2.1.2 on 2019-04-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_auto_20190331_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationaccount',
            name='permissions',
            field=models.TextField(default='{"task": false, "interview": false, "notice": false, "appraising": false, "scheduling": false, "repository": false}'),
        ),
        migrations.AlterField(
            model_name='associationdepartment',
            name='manager',
            field=models.ManyToManyField(blank=True, related_name='department_manager', to='association.AssociationAccount'),
        ),
    ]
