# Generated by Django 2.1.2 on 2019-04-02 14:00

import common.core.dao.time_stamp
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(blank=True, default='', max_length=10)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('config', models.TextField(default='{}')),
                ('create_time', common.core.dao.time_stamp.TimeStampField(default=0)),
                ('update_time', common.core.dao.time_stamp.TimeStampField(default=0)),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校表',
            },
        ),
    ]
