# Generated by Django 2.1.2 on 2019-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190329_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationtaskreport',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
