# Generated by Django 2.1.2 on 2019-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_validated', models.BooleanField(default=False)),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男生'), (2, '女生')], default=0)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('realname', models.CharField(default='', max_length=50)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, '干事'), (1, '部长'), (2, '会长'), (4, 'TEACHER'), (99, '系统管理员')], default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('phone_validated', models.BooleanField(default=False)),
                ('avator', models.CharField(blank=True, default='', max_length=200)),
                ('motto', models.CharField(blank=True, default='', max_length=60)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('permissions', models.TextField(default='{}')),
                ('temp_access_token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'LittlePigHoHo主账户表',
                'verbose_name': 'LittlePigHoHo主账户',
            },
        ),
    ]
