# Generated by Django 2.1.2 on 2019-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190317_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, '干事'), (1, '部长'), (2, '会长'), (99, '系统管理员')], default=0),
        ),
    ]
