# Generated by Django 2.1.2 on 2019-03-29 23:46

import common.core.dao.time_stamp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190327_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='update_time',
            field=common.core.dao.time_stamp.TimeStampField(default=0),
        ),
    ]
