# Generated by Django 2.1.2 on 2019-03-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
