# Generated by Django 2.1.2 on 2019-02-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtemplate',
            name='using',
            field=models.BooleanField(default=False),
        ),
    ]
