# Generated by Django 2.1.2 on 2019-03-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisingScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='{}')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.AssociationAccount')),
            ],
            options={
                'verbose_name_plural': '评分表',
                'verbose_name': '评分',
            },
        ),
        migrations.CreateModel(
            name='AppraisingScoreTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('config', models.TextField(default='{}')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.AssociationAccount')),
                ('manager', models.ManyToManyField(blank=True, related_name='score_manager', to='association.AssociationAccount')),
            ],
            options={
                'verbose_name_plural': '评分模板表',
                'verbose_name': '评分模板',
            },
        ),
        migrations.AddField(
            model_name='appraisingscore',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraising.AppraisingScoreTemplate'),
        ),
    ]
