# Generated by Django 2.1.2 on 2019-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisingscore',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='appraisingscore',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
