# Generated by Django 2.1.2 on 2019-03-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationAccountCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='{}')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.AssociationAccount')),
            ],
            options={
                'verbose_name_plural': '用户无课表',
                'verbose_name': '用户无课表',
            },
        ),
        migrations.CreateModel(
            name='AssociationCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(default='{}')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'verbose_name_plural': '无课表',
                'verbose_name': '无课表',
            },
        ),
        migrations.CreateModel(
            name='AssociationScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('config', models.TextField(default='{}')),
                ('content', models.TextField(default='{}')),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='association.AssociationAccount')),
                ('manager', models.ManyToManyField(blank=True, related_name='scheduling_manager', to='association.AssociationAccount')),
            ],
            options={
                'verbose_name_plural': '协会排班表',
                'verbose_name': '协会排班',
            },
        ),
        migrations.AddField(
            model_name='associationaccountcurriculum',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.AssociationCurriculum'),
        ),
    ]
