# Generated by Django 2.1.2 on 2019-02-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='{}')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.AssociationAccount')),
            ],
            options={
                'verbose_name': '用户无课表',
                'verbose_name_plural': '用户无课表',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(default='{}')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
            ],
            options={
                'verbose_name': '无课表',
                'verbose_name_plural': '无课表',
            },
        ),
        migrations.AddField(
            model_name='accountcurriculum',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.Curriculum'),
        ),
    ]
