# Generated by Django 2.1.2 on 2019-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationaccountcurriculum',
            name='content',
            field=models.TextField(default='{}'),
        ),
    ]
