# Generated by Django 2.1.2 on 2019-03-29 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_associationscheduling_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationaccountcurriculum',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associationaccountcurriculum',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='associationcurriculum',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associationcurriculum',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
